import {
  LayoutDashboard,
  Users,
  Route,
  BarChart3,
  LogOut,
  Settings,
  UserCheck,
  ShieldCheck,
  Plus,
  Loader2,
  Search,
  Pencil,
  Trash2,
  Eye,
  EyeOff,
  Check,
  X,
  Mail,
  User,
  Filter,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  MoreHorizontal,
  AlertTriangle,
  Building2,
  Copy,
  Key,
  Globe,
  Save,
  ArrowUp,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  CheckCircle,
  MousePointer,
  Scroll,
  Info,
  Target,
  RefreshCw,
  Undo2,
  Redo2,
  GripVertical,
  MessageSquare,
  BookOpen,
  HelpCircle,
  MousePointerClick,
  List,
  Download,
  SkipForward,
  Code,
  Navigation,
  ClipboardList,
  Video,
  CheckSquare,
  Layers,
  Grid,
  Circle,
  Square,
  Hexagon,
  Play,
  type LucideProps,
} from 'lucide-react';

export const Icons = {
  logo: (props: LucideProps) => (
    <img
      {...props}
      src="/guidora-logo-2.png"
      alt="Guidora logo"
      className={props.className}
    />
  ),
  spinner: Loader2,
  dashboard: LayoutDashboard,
  users: Users,
  tours: Route,
  analytics: BarChart3,
  logout: LogOut,
  settings: Settings,
  active: UserCheck,
  admin: ShieldCheck,
  plus: Plus,
  search: Search,
  edit: Pencil,
  trash: Trash2,
  eye: Eye,
  eyeOff: EyeOff,
  check: Check,
  close: X,
  mail: Mail,
  user: User,
  filter: Filter,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
  more: MoreHorizontal,
  warning: AlertTriangle,
  building: Building2,
  copy: Copy,
  key: Key,
  globe: Globe,
  
  // Nouvelles icônes pour l'éditeur
  save: Save,
  tooltip: MessageSquare,
  modal: LayoutDashboard,
  highlight: Target,
  form: Info,
  drag: GripVertical,
  arrowUp: ArrowUp,
  arrowDown: ArrowDown,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  checkCircle: CheckCircle,
  cursorClick: MousePointerClick,
  mousePointer: MousePointer,
  scroll: Scroll,
  info: Info,
  target: Target,
  refresh: RefreshCw,
  undo: Undo2,
  redo: Redo2,
  layout: LayoutDashboard,
  list: List,
  download: Download,
  skipForward: SkipForward,
  code: Code,
  navigation: Navigation,
  messageSquare: MessageSquare,
  clipboardList: ClipboardList,
  video: Video,
  checkSquare: CheckSquare,
  layers: Layers,
  grid: Grid,
  circle: Circle,
  square: Square,
  hexagon: Hexagon,
  play: Play,
};