import type { GuidedTour, TourAccessGrant, TourAccessMode, User } from '@/lib/types';
import type { DashboardRole } from '@/lib/dashboard-roles';
import {
	getContextualPublishedByRole,
	isContextualAutogeneratedTour,
	isDeveloperOnlyAutogenTour,
	isDeveloperOwnedTestTour,
	isSdkLabPublishedTour,
	isSdkLabTemplateTour,
} from '@/lib/tour-lab';

export type TourEnvironment = 'sandbox' | 'production';
export type TourSandboxStatus = 'pending' | 'approved' | 'rejected' | 'returned';
export type TourListEnvironmentFilter =
	| 'all'
	| 'production'
	| 'sandbox'
	| 'pending'
	| 'lecture'
	| 'collab';

const TOUR_LIST_FILTER_LABELS: Record<Exclude<TourListEnvironmentFilter, 'all'>, string> = {
	production: 'Production',
	sandbox: 'Sandbox',
	pending: 'En attente',
	lecture: 'Lecture',
	collab: 'Collab',
};

export function getTourListFilterLabel(filter: TourListEnvironmentFilter): string {
	if (filter === 'all') {
		return 'Tous';
	}
	return TOUR_LIST_FILTER_LABELS[filter];
}

export function isTourProductionDeployment(
	tour: Pick<GuidedTour, 'environment'>,
): boolean {
	return tour.environment === 'production';
}

export type TourSandboxFields = Pick<
	GuidedTour,
	| 'environment'
	| 'sandboxStatus'
	| 'createdBy'
	| 'targetUrl'
	| 'triggerConditions'
	| 'isActive'
	| 'isSandboxTestActive'
	| 'developerPrivate'
	| 'assignedAdminIds'
	| 'inCollaboration'
	| 'accessGrants'
>;

export function getTourAccessGrant(
	tour: Pick<GuidedTour, 'accessGrants'>,
	userId?: string,
	mode?: TourAccessMode,
) {
	if (!userId || !tour.accessGrants?.length) {
		return undefined;
	}
	const grant = tour.accessGrants.find((g) => g.userId === userId);
	if (!mode) {
		return grant;
	}
	return grant?.accessMode === mode ? grant : undefined;
}

export function hasTourAccessGrant(
	tour: Pick<GuidedTour, 'accessGrants'>,
	userId: string | undefined,
	mode: TourAccessMode,
): boolean {
	return Boolean(getTourAccessGrant(tour, userId, mode));
}

/** Duplication / concaténation : interdit en accès lecture seule. */
export function canForkTour(
	tour: Pick<
		GuidedTour,
		| 'accessGrants'
		| 'createdBy'
		| 'inCollaboration'
		| 'environment'
		| 'sandboxStatus'
		| 'assignedAdminIds'
		| 'targetUrl'
		| 'triggerConditions'
		| 'productionManagedByAdminId'
	>,
	role: DashboardRole | null,
	userId?: string,
): boolean {
	if (!userId || isSdkLabTemplateTour(tour)) {
		return false;
	}
	if (isTourProductionDeployment(tour)) {
		if (!isProductionManagerAdmin(tour, userId)) {
			return false;
		}
		if (tour.createdBy === userId) {
			return !isDeveloperOwnedAwaitingAdminDecision(tour, userId);
		}
		return isAdminOriginatedTour(tour);
	}
	if (isTourCollaborationPeerCard(tour, role, userId)) {
		return false;
	}
	if (tour.createdBy === userId) {
		return !isDeveloperOwnedAwaitingAdminDecision(tour, userId);
	}
	const mode = resolveTourEditorAccess(tour, role, userId, null);
	return mode !== null && mode !== 'view';
}

/** Carte limitée (export + test sandbox) : grant lecture seule hors collaboration. */
export function isTourCardViewOnly(
	tour: TourSandboxFields &
		Pick<GuidedTour, 'accessGrants' | 'createdBy' | 'inCollaboration' | 'productionManagedByAdminId'>,
	role: DashboardRole | null,
	userId?: string,
): boolean {
	if (!userId || tour.inCollaboration) {
		return false;
	}
	return resolveTourEditorAccess(tour, role, userId, null) === 'view';
}

/** Pair en collaboration sandbox (admin invité ou dev) — même barre d’actions, hors propriétaire. */
export function isTourCollaborationPeerCard(
	tour: Pick<GuidedTour, 'accessGrants' | 'createdBy' | 'inCollaboration'>,
	role: DashboardRole | null,
	userId?: string,
): boolean {
	if (!userId || tour.createdBy === userId) {
		return false;
	}
	return resolveTourEditorAccess(tour, role, userId, null) === 'collaborate';
}

/** @deprecated Utiliser isTourCardViewOnly */
export function isAdminTourCardViewOnly(
	tour: Pick<GuidedTour, 'accessGrants' | 'createdBy' | 'inCollaboration'>,
	role: DashboardRole | null,
	userId?: string,
): boolean {
	return isTourCardViewOnly(tour, role, userId);
}

export function canManageTourSharing(
	tour: TourSandboxFields & Pick<GuidedTour, 'assignedAdminIds' | 'targetUrl' | 'triggerConditions'>,
	role: DashboardRole | null,
	userId?: string,
): boolean {
	if (isSdkLabPublishedTour(tour)) {
		return false;
	}
	if (tour.environment !== 'sandbox') {
		return false;
	}
	if (
		tour.sandboxStatus === 'approved' &&
		isDeveloperOriginatedTour(tour)
	) {
		return false;
	}
	if (isDeveloperOwnedAwaitingAdminDecision(tour, userId)) {
		return false;
	}
	if (!userId || tour.createdBy !== userId) {
		return false;
	}
	if (isTourCardViewOnly(tour, role, userId) || isTourCollaborationPeerCard(tour, role, userId)) {
		return false;
	}
	return role === 'DEVELOPER' || role === 'ADMIN';
}

export type TourEditorAccessMode = 'owner' | 'collaborate' | 'view' | 'admin';

export function resolveTourEditorAccess(
	tour: TourSandboxFields & Pick<GuidedTour, 'accessGrants'>,
	role: DashboardRole | null,
	userId?: string,
	accessParam?: string | null,
): TourEditorAccessMode | null {
	if (!userId) {
		return null;
	}
	if (isAdminOriginatedProductionTour(tour)) {
		const managerId = resolveProductionManagerAdminId(tour);
		if (userId === managerId) {
			return tour.createdBy === userId ? 'owner' : 'admin';
		}
		return 'view';
	}
	if (tour.createdBy === userId) {
		return 'owner';
	}
	if (hasTourAccessGrant(tour, userId, 'collaborate')) {
		return 'collaborate';
	}
	if (hasTourAccessGrant(tour, userId, 'view')) {
		return 'view';
	}
	if (role === 'ADMIN' && tour.inCollaboration) {
		return 'collaborate';
	}
	if (role === 'ADMIN' && !tour.inCollaboration) {
		return 'admin';
	}
	if (accessParam === 'view' || accessParam === 'collaborate') {
		return null;
	}
	return null;
}

export function canAccessTourEditor(
	tour: TourSandboxFields & Pick<GuidedTour, 'accessGrants' | 'targetUrl' | 'triggerConditions'>,
	role: DashboardRole | null,
	userId?: string,
	accessParam?: string | null,
): boolean {
	if (isTourProductionDeployment(tour)) {
		return false;
	}
	const mode = resolveTourEditorAccess(tour, role, userId, accessParam);
	if (!mode) {
		return false;
	}
	if (accessParam === 'view') {
		return mode === 'view' || mode === 'owner' || mode === 'admin';
	}
	if (accessParam === 'collaborate') {
		return mode === 'collaborate' || mode === 'owner';
	}
	return (
		mode === 'owner' ||
		mode === 'admin' ||
		mode === 'collaborate' ||
		mode === 'view' ||
		canManageSandboxTour(tour, role, userId)
	);
}

export function isTourEditorReadOnly(
	tour: Pick<
		GuidedTour,
		| 'accessGrants'
		| 'createdBy'
		| 'inCollaboration'
		| 'environment'
		| 'sandboxStatus'
		| 'assignedAdminIds'
	>,
	role: DashboardRole | null,
	userId?: string,
	accessParam?: string | null,
): boolean {
	if (accessParam === 'view') {
		return true;
	}
	const mode = resolveTourEditorAccess(tour, role, userId, accessParam);
	if (mode === 'view') {
		return true;
	}
	return (
		mode === 'owner' &&
		role === 'DEVELOPER' &&
		isDeveloperOwnedAwaitingAdminDecision(tour, userId)
	);
}

export function canEditTourWithGrants(
	tour: TourSandboxFields & Pick<GuidedTour, 'accessGrants' | 'targetUrl' | 'triggerConditions'>,
	role: DashboardRole | null,
	userId?: string,
): boolean {
	const mode = resolveTourEditorAccess(tour, role, userId, null);
	if (mode === 'view') {
		return false;
	}
	if (mode === 'collaborate') {
		if (tour.environment !== 'sandbox') {
			return false;
		}
		if (isDeveloperOriginatedTour(tour) && tour.sandboxStatus === 'approved') {
			return false;
		}
		return true;
	}
	if (mode === 'owner') {
		return canManageSandboxTour(tour, role, userId) || role === 'ADMIN';
	}
	if (mode === 'admin') {
		return role === 'ADMIN';
	}
	return false;
}

export function normalizeAssignedAdminIds(ids?: string[] | null): string[] {
	return Array.isArray(ids) ? ids.filter((id) => typeof id === 'string' && id.length > 0) : [];
}

/** Payload PUT access-grants : uniquement userId + accessMode (pas les champs renvoyés par l’API). */
export function toTourAccessGrantPayload(
	grants: ReadonlyArray<Pick<TourAccessGrant, 'userId' | 'accessMode'>> | undefined,
): Array<{ userId: string; accessMode: TourAccessMode }> {
	if (!grants?.length) {
		return [];
	}
	const unique = new Map<string, TourAccessMode>();
	for (const grant of grants) {
		const userId = grant.userId?.trim();
		if (!userId) {
			continue;
		}
		unique.set(userId, grant.accessMode);
	}
	return [...unique.entries()].map(([userId, accessMode]) => ({ userId, accessMode }));
}

/**
 * Modérateur admin dédié exclu des pickers lecture seule et collaboration
 * après un cycle modération (assignation → retour / rejet / transfert).
 */
export function getDedicatedModeratorExcludedFromSharePickerIds(
	tour: Pick<
		GuidedTour,
		| 'environment'
		| 'assignedAdminIds'
		| 'assignedToAdminsAt'
		| 'sandboxStatus'
		| 'sandboxRejectedBy'
	>,
): string[] {
	if (!hasDeveloperModerationSubmissionHistory(tour)) {
		return [];
	}
	const dedicatedId = getDedicatedModeratorAdminId(tour);
	return dedicatedId ? [dedicatedId] : [];
}

/** @deprecated Préférer getDedicatedModeratorExcludedFromSharePickerIds */
export const getCollaborationExcludedAdminIds = getDedicatedModeratorExcludedFromSharePickerIds;

/** Modérateur admin dédié (assignation unique ou dernier acteur de modération). */
export function getDedicatedModeratorAdminId(
	tour: Pick<GuidedTour, 'assignedAdminIds' | 'sandboxRejectedBy'>,
): string | null {
	const assigned = normalizeAssignedAdminIds(tour.assignedAdminIds);
	if (assigned.length === 1) {
		return assigned[0];
	}
	return tour.sandboxRejectedBy ?? null;
}

/** Rejet, retour ou transfert : masqué côté admin jusqu’à réassignation développeur. */
export function isDeveloperModerationRevokedFromAdmin(
	tour: Pick<GuidedTour, 'developerPrivate' | 'sandboxStatus'>,
): boolean {
	return (
		Boolean(tour.developerPrivate) &&
		(tour.sandboxStatus === 'rejected' || tour.sandboxStatus === 'returned')
	);
}

/** Après retour / rejet / transfert, le développeur doit renvoyer au même modérateur. */
export function mustReassignToDedicatedModerator(
	tour: Pick<GuidedTour, 'sandboxStatus' | 'assignedAdminIds' | 'sandboxRejectedBy'>,
): boolean {
	return (
		(tour.sandboxStatus === 'returned' || tour.sandboxStatus === 'rejected') &&
		Boolean(getDedicatedModeratorAdminId(tour))
	);
}

export function isDeveloperPrivateUnassigned(tour: TourSandboxFields): boolean {
	return Boolean(tour.developerPrivate) && normalizeAssignedAdminIds(tour.assignedAdminIds).length === 0;
}

export function isTourSharedWithMembers(
	tour: Pick<GuidedTour, 'sharingHasView' | 'sharingHasCollaborate'>,
): boolean {
	return Boolean(tour.sharingHasView || tour.sharingHasCollaborate);
}

export function isTourAssignedToAdmin(tour: TourSandboxFields, adminId?: string): boolean {
	if (!adminId) {
		return false;
	}
	return normalizeAssignedAdminIds(tour.assignedAdminIds).includes(adminId);
}

export type TourActivationAudience = 'sandbox' | 'production';

export function isSandboxTour(tour: TourSandboxFields): boolean {
	return tour.environment === 'sandbox';
}

export function isDeveloperTestTour(
	tour: TourSandboxFields,
	role: DashboardRole | null,
	userId?: string,
): boolean {
	return role === 'DEVELOPER' && isDeveloperOwnedTestTour(tour, userId);
}

export function isPendingSandboxTour(tour: TourSandboxFields): boolean {
	return tour.environment === 'sandbox' && tour.sandboxStatus === 'pending';
}

export function isRejectedSandboxTour(tour: TourSandboxFields): boolean {
	return tour.environment === 'sandbox' && tour.sandboxStatus === 'rejected';
}

export function isReturnedSandboxTour(tour: TourSandboxFields): boolean {
	return tour.environment === 'sandbox' && tour.sandboxStatus === 'returned';
}

export function isDeveloperOwnedSandboxTour(
	tour: TourSandboxFields,
	userId?: string,
): boolean {
	return isSandboxTour(tour) && Boolean(userId) && tour.createdBy === userId;
}

export function hasDeveloperSubmissionMessage(
	tour: Pick<GuidedTour, 'developerSubmissionMessage'>,
): boolean {
	return Boolean(tour.developerSubmissionMessage?.trim());
}

export function hasDeveloperViewShareMessage(
	tour: Pick<GuidedTour, 'developerViewShareMessage'>,
): boolean {
	return Boolean(tour.developerViewShareMessage?.trim());
}

export function hasDeveloperCollaborateShareMessage(
	tour: Pick<GuidedTour, 'developerCollaborateShareMessage'>,
): boolean {
	return Boolean(tour.developerCollaborateShareMessage?.trim());
}

export type TourShareMessageMode = 'view' | 'collaborate';

export function getDeveloperShareMessage(
	tour: Pick<GuidedTour, 'developerViewShareMessage' | 'developerCollaborateShareMessage'>,
	mode: TourShareMessageMode,
): string | null {
	const raw =
		mode === 'view' ? tour.developerViewShareMessage : tour.developerCollaborateShareMessage;
	return raw?.trim() || null;
}

export function getDeveloperShareMessageAt(
	tour: Pick<
		GuidedTour,
		'developerViewShareMessageAt' | 'developerCollaborateShareMessageAt'
	>,
	mode: TourShareMessageMode,
): string | null {
	return mode === 'view'
		? tour.developerViewShareMessageAt ?? null
		: tour.developerCollaborateShareMessageAt ?? null;
}

/** Parcours sandbox ayant déjà transité par une assignation admin (cycle modération). */
export function hasDeveloperModerationSubmissionHistory(
	tour: TourSandboxFields &
		Pick<GuidedTour, 'assignedAdminIds' | 'assignedToAdminsAt' | 'sandboxRejectedBy'>,
): boolean {
	if (tour.environment !== 'sandbox') {
		return false;
	}
	if (tour.assignedToAdminsAt) {
		return true;
	}
	if (normalizeAssignedAdminIds(tour.assignedAdminIds).length > 0) {
		return true;
	}
	if (tour.sandboxRejectedBy) {
		return true;
	}
	return tour.sandboxStatus === 'rejected' || tour.sandboxStatus === 'returned';
}

/** Propriétaire développeur : suppression autorisée uniquement avant toute soumission modération. */
export function canDeveloperDeleteOwnedSandboxTour(
	tour: TourSandboxFields &
		Pick<GuidedTour, 'assignedAdminIds' | 'assignedToAdminsAt' | 'sandboxRejectedBy'>,
	userId?: string,
): boolean {
	if (!isDeveloperOwnedSandboxTour(tour, userId)) {
		return false;
	}
	return !hasDeveloperModerationSubmissionHistory(tour);
}

/** Parcours sandbox propriétaire assigné à un admin, en attente de décision. */
export function isDeveloperOwnedAwaitingAdminDecision(
	tour: TourSandboxFields & Pick<GuidedTour, 'assignedAdminIds'>,
	userId?: string,
): boolean {
	return (
		isDeveloperOwnedSandboxTour(tour, userId) &&
		tour.sandboxStatus === 'pending' &&
		normalizeAssignedAdminIds(tour.assignedAdminIds).length > 0
	);
}

/** Sandbox développeur modifiable (pending non assigné / rejected / returned), pas après approbation. */
export function isDeveloperSandboxEditable(
	tour: TourSandboxFields & Pick<GuidedTour, 'assignedAdminIds'>,
	userId?: string,
): boolean {
	if (!isDeveloperOwnedSandboxTour(tour, userId)) {
		return false;
	}
	if (isDeveloperOwnedAwaitingAdminDecision(tour, userId)) {
		return false;
	}
	return tour.sandboxStatus !== 'approved';
}

export function canManageSandboxTour(
	tour: TourSandboxFields,
	role: DashboardRole | null,
	userId?: string,
): boolean {
	return role === 'DEVELOPER' && isDeveloperSandboxEditable(tour, userId);
}

/** Activer/désactiver un parcours sandbox ou autogénéré pour test SDK (créateur uniquement). */
export function canToggleSandboxTourActive(
	tour: TourSandboxFields,
	role: DashboardRole | null,
	userId?: string,
): boolean {
	return isDeveloperTestTour(tour, role, userId) && isDeveloperSandboxEditable(tour, userId);
}

/** Parcours visible en test sandbox (avant ou après approbation). */
export function isTourSandboxTestActive(tour: TourSandboxFields): boolean {
	if (tour.environment === 'sandbox') {
		return Boolean(tour.isActive);
	}
	return Boolean(tour.isSandboxTestActive);
}

/** Met à jour l’état local du sélecteur « Test (actif) » dans l’éditeur. */
export function patchTourSandboxTestActive(
	tour: TourSandboxFields,
	active: boolean,
): Pick<GuidedTour, 'isActive' | 'isSandboxTestActive'> {
	if (tour.environment === 'sandbox') {
		return { isActive: active };
	}
	return { isSandboxTestActive: active };
}

/** Retire l’activation test du payload PUT : elle passe par `/activate` (audience sandbox). */
export function omitSandboxTestActivationFromSavePayload(
	payload: GuidedTourSavePayload,
	tour: TourSandboxFields,
): GuidedTourSavePayload {
	if (tour.environment === 'sandbox') {
		const { isActive: _isActive, ...rest } = payload;
		return rest;
	}
	const { isSandboxTestActive: _isSandboxTestActive, ...rest } = payload as GuidedTourSavePayload & {
		isSandboxTestActive?: boolean;
	};
	return rest;
}

/** Parcours visible pour les utilisateurs finaux (production). */
export function isTourProductionActive(tour: TourSandboxFields): boolean {
	return tour.environment === 'production' && Boolean(tour.isActive);
}

export function canToggleAdminSandboxTest(
	tour: TourSandboxFields,
	role: DashboardRole | null,
): boolean {
	if (role !== 'ADMIN') {
		return false;
	}
	if (isSandboxTour(tour)) {
		return true;
	}
	// Admin can run sandbox tests on any production tour, including direct
	// production creations where sandboxStatus is null.
	return tour.environment === 'production';
}

export function canToggleAdminProduction(tour: TourSandboxFields, role: DashboardRole | null): boolean {
	return role === 'ADMIN' && tour.environment === 'production';
}

export type TourCreatorRoleLookup = ReadonlyMap<string, 'ADMIN' | 'DEVELOPER' | 'USER'>;

type TourOriginFields = TourSandboxFields & Pick<GuidedTour, 'triggerConditions' | 'createdBy'>;

/** Parcours issu d’un développeur (file modération), distinct de l’environnement sandbox admin. */
export function isDeveloperOriginatedTour(
	tour: TourOriginFields,
	creatorRoleByUserId?: TourCreatorRoleLookup,
): boolean {
	const publishedRole = getContextualPublishedByRole(tour)?.toUpperCase();
	const createdBy = tour.createdBy?.trim();
	const creatorRole = createdBy ? creatorRoleByUserId?.get(createdBy) : undefined;

	if (publishedRole === 'ADMIN') {
		return false;
	}
	if (publishedRole === 'DEVELOPER') {
		return true;
	}
	if (publishedRole === 'SDK_TOKEN') {
		if (!createdBy) {
			return false;
		}
		if (Boolean(tour.developerPrivate)) {
			return true;
		}
		if (normalizeAssignedAdminIds(tour.assignedAdminIds).length > 0) {
			return true;
		}
		if (tour.sandboxStatus === 'approved') {
			return true;
		}
		return creatorRole === 'DEVELOPER';
	}

	if (isContextualAutogeneratedTour(tour)) {
		// Autogen legacy en sandbox : developerPrivate distingue admin (false) vs développeur (true).
		if (tour.environment !== 'sandbox' || !createdBy) {
			if (creatorRole === 'DEVELOPER' && tour.sandboxStatus === 'approved') {
				return true;
			}
			return false;
		}
		if (creatorRole === 'ADMIN') {
			return false;
		}
		if (creatorRole === 'DEVELOPER') {
			return true;
		}
		return Boolean(tour.developerPrivate);
	}

	if (!createdBy) {
		return false;
	}

	if (creatorRole === 'ADMIN') {
		return false;
	}
	if (creatorRole === 'DEVELOPER') {
		return true;
	}

	// Parcours manuel sans rôle créateur connu : aligné backend via developerPrivate.
	return Boolean(tour.developerPrivate);
}

/** Parcours admin (hors file modération développeur). */
export function isAdminOriginatedTour(
	tour: TourOriginFields,
	creatorRoleByUserId?: TourCreatorRoleLookup,
): boolean {
	return Boolean(tour.createdBy?.trim()) && !isDeveloperOriginatedTour(tour, creatorRoleByUserId);
}

/** Parcours admin en sandbox : visible uniquement par le propriétaire (+ invités par grant). */
export function isAdminSandboxPrivateTour(
	tour: TourOriginFields,
	creatorRoleByUserId?: TourCreatorRoleLookup,
): boolean {
	return isAdminOriginatedTour(tour, creatorRoleByUserId) && tour.environment === 'sandbox';
}

/** Parcours admin publié en production (gestion déléguée possible). */
export function isAdminOriginatedProductionTour(
	tour: TourOriginFields,
	creatorRoleByUserId?: TourCreatorRoleLookup,
): boolean {
	return isTourProductionDeployment(tour) && isAdminOriginatedTour(tour, creatorRoleByUserId);
}

export function resolveProductionManagerAdminId(
	tour: Pick<GuidedTour, 'createdBy' | 'productionManagedByAdminId'>,
): string | null {
	if (tour.productionManagedByAdminId) {
		return tour.productionManagedByAdminId;
	}
	return tour.createdBy ?? null;
}

export function isProductionManagerAdmin(
	tour: TourOriginFields,
	userId?: string,
	creatorRoleByUserId?: TourCreatorRoleLookup,
): boolean {
	if (!userId || !isAdminOriginatedProductionTour(tour, creatorRoleByUserId)) {
		return false;
	}
	return resolveProductionManagerAdminId(tour) === userId;
}

/** Propriétaire créateur : déléguer ou reprendre la gestion prod. */
export function canDelegateProductionManagement(
	tour: TourOriginFields,
	role: DashboardRole | null,
	userId?: string,
	creatorRoleByUserId?: TourCreatorRoleLookup,
): boolean {
	return (
		role === 'ADMIN' &&
		Boolean(userId) &&
		tour.createdBy === userId &&
		isAdminOriginatedProductionTour(tour, creatorRoleByUserId)
	);
}

/** Badge « Privé » propriétaire : dev non assigné ou admin en sandbox sans partage actif. */
export function isTourOwnerPrivateUnshared(
	tour: TourSandboxFields & Pick<GuidedTour, 'sharingHasView' | 'sharingHasCollaborate' | 'createdBy'>,
	userId?: string,
	creatorRoleByUserId?: TourCreatorRoleLookup,
): boolean {
	if (!userId || tour.createdBy !== userId || isTourSharedWithMembers(tour)) {
		return false;
	}
	return (
		isDeveloperPrivateUnassigned(tour) ||
		isAdminSandboxPrivateTour(tour, creatorRoleByUserId)
	);
}

/** Sandbox approuvé via workflow dev → admin (badge « Approuvé »). */
export function isDeveloperModerationApprovedSandbox(
	tour: TourOriginFields,
	creatorRoleByUserId?: TourCreatorRoleLookup,
): boolean {
	return (
		tour.environment === 'sandbox' &&
		tour.sandboxStatus === 'approved' &&
		isDeveloperOriginatedTour(tour, creatorRoleByUserId)
	);
}

/** Partage lecture/collab verrouillé après approbation modération développeur. */
export function isTourSharingLockedByDeveloperApproval(
	tour: TourOriginFields,
	creatorRoleByUserId?: TourCreatorRoleLookup,
): boolean {
	return (
		tour.sandboxStatus === 'approved' &&
		isDeveloperOriginatedTour(tour, creatorRoleByUserId)
	);
}

/** En attente de validation admin (parcours développeur uniquement). */
export function isDeveloperSubmittedPendingSandbox(
	tour: TourOriginFields,
	creatorRoleByUserId?: TourCreatorRoleLookup,
	viewer?: { role: DashboardRole | null; userId?: string },
): boolean {
	if (!isPendingSandboxTour(tour) || !isDeveloperOriginatedTour(tour, creatorRoleByUserId)) {
		return false;
	}
	if (viewer?.role === 'DEVELOPER') {
		return (
			isPendingSandboxTour(tour) &&
			normalizeAssignedAdminIds(tour.assignedAdminIds).length > 0
		);
	}
	if (viewer?.role === 'ADMIN') {
		return isTourAssignedToAdmin(tour, viewer.userId);
	}
	return isPendingSandboxTour(tour) && isDeveloperOriginatedTour(tour, creatorRoleByUserId);
}

/** Rejet après modération (parcours développeur uniquement). */
export function isDeveloperModerationRejectedTour(
	tour: TourOriginFields,
	creatorRoleByUserId?: TourCreatorRoleLookup,
): boolean {
	return isRejectedSandboxTour(tour) && isDeveloperOriginatedTour(tour, creatorRoleByUserId);
}

/** Renvoi admin après approbation — visible côté développeur propriétaire. */
export function isDeveloperModerationReturnedTour(
	tour: TourSandboxFields & Pick<GuidedTour, 'createdBy'>,
	userId?: string,
): boolean {
	return isReturnedSandboxTour(tour) && isDeveloperOwnedSandboxTour(tour, userId);
}

const OWNERSHIP_TRANSFER_REASON_PREFIX = 'Parcours transféré à un autre développeur';

/** Parcours renvoyé suite à un transfert de propriété (distinct du renvoi modération classique). */
export function isOwnershipTransferReturn(
	tour: Pick<GuidedTour, 'sandboxStatus' | 'sandboxRejectionReason'>,
): boolean {
	return (
		tour.sandboxStatus === 'returned' &&
		Boolean(tour.sandboxRejectionReason?.includes(OWNERSHIP_TRANSFER_REASON_PREFIX))
	);
}

/** Motif lisible affiché dans le badge / modal Transféré. */
export function getOwnershipTransferMessage(
	tour: Pick<GuidedTour, 'sandboxRejectionReason'>,
): string | null {
	if (!isOwnershipTransferReturn(tour)) {
		return null;
	}
	const reason = tour.sandboxRejectionReason?.trim() ?? '';
	const marker = 'Motif : ';
	const markerIndex = reason.indexOf(marker);
	if (markerIndex >= 0) {
		return reason.slice(markerIndex + marker.length).trim() || null;
	}
	return reason || null;
}

/** Ancien propriétaire : accès lecture conservé après transfert. */
export function isPreviousOwnerOfTransferredTour(
	tour: Pick<GuidedTour, 'createdBy' | 'sandboxStatus' | 'sandboxRejectionReason' | 'accessGrants'>,
	userId?: string,
): boolean {
	if (!userId || !isOwnershipTransferReturn(tour) || tour.createdBy === userId) {
		return false;
	}
	return hasTourAccessGrant(tour, userId, 'view');
}

export function formatTourActorLabel(
	user?: Pick<User, 'firstName' | 'lastName' | 'email'> | null,
	fallback = 'Administrateur',
): string {
	if (!user) {
		return fallback;
	}
	const name = [user.firstName, user.lastName].filter(Boolean).join(' ').trim();
	return name ? `${name} (${user.email})` : user.email || fallback;
}

export function resolveTourActorLabel(
	actorId: string | null | undefined,
	usersById?: ReadonlyMap<string, Pick<User, 'firstName' | 'lastName' | 'email'>>,
	sessionUser?: Pick<User, 'id' | 'firstName' | 'lastName' | 'email'> | null,
): string {
	if (!actorId) {
		return 'Inconnu';
	}
	if (sessionUser?.id === actorId) {
		return formatTourActorLabel(sessionUser, 'Vous');
	}
	return formatTourActorLabel(usersById?.get(actorId), 'Administrateur');
}

/** Libellé court pour le badge « Gestion » (évite le chevauchement avec le titre / la date). */
export function formatProductionManagerShortLabel(
	actorId: string | null | undefined,
	usersById?: ReadonlyMap<string, Pick<User, 'firstName' | 'lastName' | 'email'>>,
	sessionUser?: Pick<User, 'id' | 'firstName' | 'lastName' | 'email'> | null,
): string {
	if (!actorId) {
		return 'Inconnu';
	}
	if (sessionUser?.id === actorId) {
		return 'Vous';
	}
	const user = usersById?.get(actorId);
	const name = [user?.firstName, user?.lastName].filter(Boolean).join(' ').trim();
	if (name) {
		return name;
	}
	const email = user?.email?.trim();
	if (email) {
		const local = email.split('@')[0]?.trim();
		return local || email;
	}
	return 'Admin';
}

/** Nouveau propriétaire pendant la phase transférée (jusqu’à réassignation admin). */
export function isNewOwnerOfTransferredTour(
	tour: Pick<GuidedTour, 'createdBy' | 'sandboxStatus' | 'sandboxRejectionReason'>,
	userId?: string,
): boolean {
	return (
		Boolean(userId) &&
		tour.createdBy === userId &&
		isOwnershipTransferReturn(tour)
	);
}

export function canApproveSandboxTour(
	tour: TourSandboxFields &
		Pick<GuidedTour, 'triggerConditions' | 'createdBy' | 'accessGrants' | 'inCollaboration'>,
	role: DashboardRole | null,
	creatorRoleByUserId?: TourCreatorRoleLookup,
	viewerUserId?: string,
): boolean {
	if (isTourCollaborationPeerCard(tour, role, viewerUserId)) {
		return false;
	}
	return (
		role === 'ADMIN' &&
		isDeveloperSubmittedPendingSandbox(tour, creatorRoleByUserId, {
			role,
			userId: viewerUserId,
		})
	);
}

export function canRejectSandboxTour(
	tour: TourSandboxFields &
		Pick<GuidedTour, 'triggerConditions' | 'createdBy' | 'accessGrants' | 'inCollaboration'>,
	role: DashboardRole | null,
	creatorRoleByUserId?: TourCreatorRoleLookup,
	viewerUserId?: string,
): boolean {
	if (isTourCollaborationPeerCard(tour, role, viewerUserId)) {
		return false;
	}
	return (
		role === 'ADMIN' &&
		isDeveloperSubmittedPendingSandbox(tour, creatorRoleByUserId, {
			role,
			userId: viewerUserId,
		})
	);
}

export function canDeveloperAssignTourToAdmins(
	tour: TourSandboxFields & Pick<GuidedTour, 'assignedAdminIds'>,
	role: DashboardRole | null,
	userId?: string,
): boolean {
	return (
		role === 'DEVELOPER' &&
		isDeveloperOwnedSandboxTour(tour, userId) &&
		tour.sandboxStatus !== 'approved' &&
		!isDeveloperOwnedAwaitingAdminDecision(tour, userId) &&
		!tour.inCollaboration
	);
}

/** Parcours passé par le workflow dev → assignation admin → approbation. */
function isApprovedDeveloperModeratedTour(
	tour: TourSandboxFields & Pick<GuidedTour, 'assignedAdminIds'>,
): boolean {
	return (
		tour.sandboxStatus === 'approved' &&
		normalizeAssignedAdminIds(tour.assignedAdminIds).length > 0
	);
}

/** Admin : renvoyer un parcours approuvé au développeur pour révision (révoque l’approbation). */
export function canReopenApprovedDeveloperTour(
	tour: TourSandboxFields & TourOriginFields,
	role: DashboardRole | null,
	creatorRoleByUserId?: TourCreatorRoleLookup,
	viewerUserId?: string,
): boolean {
	if (isTourCollaborationPeerCard(tour, role, viewerUserId)) {
		return false;
	}
	return role === 'ADMIN' && isSandboxTour(tour) && isApprovedDeveloperModeratedTour(tour);
}

/** Admin : réassigner la modération à d’autres administrateurs (garde l’approbation). */
export function canReassignApprovedTourAdmins(
	tour: TourSandboxFields & TourOriginFields,
	role: DashboardRole | null,
	_creatorRoleByUserId?: TourCreatorRoleLookup,
	viewerUserId?: string,
): boolean {
	if (isTourCollaborationPeerCard(tour, role, viewerUserId)) {
		return false;
	}
	return role === 'ADMIN' && isApprovedDeveloperModeratedTour(tour);
}

/** Admin : transférer la propriété à un autre développeur (audit + badge Transféré pour le nouveau propriétaire). */
export function canTransferApprovedDeveloperTour(
	tour: TourSandboxFields & TourOriginFields,
	role: DashboardRole | null,
	_creatorRoleByUserId?: TourCreatorRoleLookup,
	viewerUserId?: string,
): boolean {
	if (isTourCollaborationPeerCard(tour, role, viewerUserId)) {
		return false;
	}
	return role === 'ADMIN' && isSandboxTour(tour) && isApprovedDeveloperModeratedTour(tour);
}

/**
 * Promotion sandbox → production (admin) : autorisée seulement après approbation
 * pour les parcours développeur (rejeté ou en attente bloquent le passage prod).
 */
/** Switcher sandbox ↔ prod : propriétaire admin pour ses parcours ; modérateur pour les parcours développeur. */
export function canAdminTransferTourEnvironment(
	tour: TourSandboxFields &
		Pick<
			GuidedTour,
			| 'accessGrants'
			| 'createdBy'
			| 'inCollaboration'
			| 'triggerConditions'
			| 'developerPrivate'
			| 'assignedAdminIds'
		>,
	role: DashboardRole | null,
	userId?: string,
	creatorRoleByUserId?: TourCreatorRoleLookup,
): boolean {
	if (role !== 'ADMIN' || !userId) {
		return false;
	}
	if (isTourCardViewOnly(tour, role, userId) || isTourCollaborationPeerCard(tour, role, userId)) {
		return false;
	}
	if (isAdminOriginatedTour(tour, creatorRoleByUserId)) {
		if (isTourProductionDeployment(tour)) {
			return isProductionManagerAdmin(tour, userId, creatorRoleByUserId);
		}
		return tour.createdBy === userId;
	}
	if (tour.createdBy === userId) {
		return true;
	}
	return resolveTourEditorAccess(tour, role, userId, null) === 'admin';
}

/** Repasser un parcours admin de prod → sandbox : réservé au propriétaire créateur. */
export function canAdminTransferProductionToSandbox(
	tour: TourOriginFields,
	role: DashboardRole | null,
	userId?: string,
	creatorRoleByUserId?: TourCreatorRoleLookup,
): boolean {
	if (tour.environment !== 'production') {
		return true;
	}
	if (!isAdminOriginatedTour(tour, creatorRoleByUserId)) {
		return canAdminTransferTourEnvironment(tour, role, userId, creatorRoleByUserId);
	}
	return Boolean(userId) && tour.createdBy === userId;
}

export function canAdminTransferSandboxToProduction(
	tour: TourOriginFields,
	creatorRoleByUserId?: TourCreatorRoleLookup,
): boolean {
	if (tour.environment !== 'sandbox') {
		return true;
	}
	if (isDeveloperSubmittedPendingSandbox(tour, creatorRoleByUserId)) {
		return false;
	}
	if (isDeveloperModerationRejectedTour(tour, creatorRoleByUserId)) {
		return false;
	}
	if (isReturnedSandboxTour(tour)) {
		return false;
	}
	return true;
}

export function matchesTourEnvironmentFilter(
	tour: TourSandboxFields,
	filter: TourListEnvironmentFilter,
): boolean {
	switch (filter) {
		case 'production':
			return tour.environment === 'production' || !tour.environment;
		case 'sandbox':
			return tour.environment === 'sandbox' || isDeveloperOnlyAutogenTour(tour);
		case 'pending':
			return isPendingSandboxTour(tour);
		case 'lecture':
			return Boolean(
				(tour as Pick<GuidedTour, 'sharingHasView'>).sharingHasView,
			);
		case 'collab':
			return Boolean(
				(tour as Pick<GuidedTour, 'sharingHasCollaborate'>).sharingHasCollaborate,
			);
		default:
			return true;
	}
}

export type ProjectHubTourAccessFields = TourSandboxFields &
	Pick<
		GuidedTour,
		| 'accessGrants'
		| 'createdBy'
		| 'inCollaboration'
		| 'assignedAdminIds'
		| 'targetUrl'
		| 'triggerConditions'
		| 'productionManagedByAdminId'
		| 'developerPrivate'
		| 'sandboxRejectionReason'
	> & {
		id?: string;
	};

/** Aligné sur le bouton « Éditer » de la liste Parcours (hub projet). */
export function canOpenProjectHubTourEditor(
	tour: ProjectHubTourAccessFields,
	role: DashboardRole | null,
	userId?: string,
): boolean {
	if (!tour.id || !userId || !role) {
		return false;
	}
	if (isTourProductionDeployment(tour)) {
		return false;
	}
	if (isPreviousOwnerOfTransferredTour(tour, userId)) {
		return false;
	}
	if (isTourCardViewOnly(tour, role, userId)) {
		return false;
	}
	if (isDeveloperOwnedAwaitingAdminDecision(tour, userId)) {
		return false;
	}
	if (isTourCollaborationPeerCard(tour, role, userId)) {
		return canEditTourWithGrants(tour, role, userId);
	}
	if (role === 'DEVELOPER') {
		return isDeveloperOwnedSandboxTour(tour, userId) && isDeveloperSandboxEditable(tour, userId);
	}
	if (role === 'ADMIN') {
		if (
			isDeveloperModerationRevokedFromAdmin(tour) &&
			!isTourAssignedToAdmin(tour, userId)
		) {
			return false;
		}
		if (
			Boolean(tour.developerPrivate) &&
			tour.sandboxStatus === 'approved' &&
			normalizeAssignedAdminIds(tour.assignedAdminIds).length > 0 &&
			!isTourAssignedToAdmin(tour, userId)
		) {
			return false;
		}
		return canEditTourWithGrants(tour, role, userId);
	}
	return false;
}

export function getProjectHubTourEditorBlockReason(
	tour: ProjectHubTourAccessFields,
	role: DashboardRole | null,
	userId?: string,
): string | null {
	if (canOpenProjectHubTourEditor(tour, role, userId)) {
		return null;
	}
	if (isTourProductionDeployment(tour)) {
		return 'Parcours en production — gérez-le depuis la liste Parcours';
	}
	if (isPreviousOwnerOfTransferredTour(tour, userId)) {
		return 'Transféré — accès lecture seule sur ce parcours';
	}
	if (isDeveloperOwnedAwaitingAdminDecision(tour, userId)) {
		return 'En attente de décision administrateur';
	}
	if (
		role === 'DEVELOPER' &&
		tour.createdBy === userId &&
		tour.sandboxStatus === 'approved'
	) {
		return 'Approuvé — édition réservée à l’administrateur';
	}
	if (
		role === 'ADMIN' &&
		isDeveloperModerationRevokedFromAdmin(tour) &&
		!isTourAssignedToAdmin(tour, userId)
	) {
		return 'Renvoyé au développeur — modération suspendue pour vous';
	}
	if (
		role === 'ADMIN' &&
		Boolean(tour.developerPrivate) &&
		tour.sandboxStatus === 'approved' &&
		normalizeAssignedAdminIds(tour.assignedAdminIds).length > 0 &&
		!isTourAssignedToAdmin(tour, userId)
	) {
		return 'Réassigné à un autre administrateur — édition indisponible';
	}
	if (isTourCardViewOnly(tour, role, userId)) {
		return 'Accès lecture seule — édition indisponible';
	}
	if (isTourCollaborationPeerCard(tour, role, userId)) {
		return 'Collaboration — édition indisponible (parcours approuvé ou hors sandbox)';
	}
	return 'Édition indisponible pour ce parcours';
}
