import type { GuidedTour, GuidedTourSavePayload } from '@/lib/types';
import type { DashboardRole } from '@/lib/dashboard-roles';
import { canManageTours } from '@/lib/dashboard-roles';
import {
	canAccessTourEditor,
	isTourProductionDeployment,
	canDeveloperDeleteOwnedSandboxTour,
	canManageSandboxTour,
	hasTourAccessGrant,
	isDeveloperOwnedSandboxTour,
	isTourCardViewOnly,
	isTourCollaborationPeerCard,
	type TourSandboxFields,
} from '@/lib/tour-sandbox';

export type TourLabEligibility = Pick<GuidedTour, 'targetUrl' | 'triggerConditions' | 'environment' | 'sandboxStatus'>;

export const SDK_LAB_TARGET_PATH_SEGMENT = '/dashboard/sdk-tests/';

/** Parcours publiés via le moteur contextuel (lab SDK, app de test, etc.). */
export function isContextualAutogeneratedTour(tour: TourLabEligibility): boolean {
	const triggerConditions = tour.triggerConditions;
	if (!triggerConditions || typeof triggerConditions !== 'object') {
		return false;
	}

	if (triggerConditions.source === 'contextual-engine') {
		return true;
	}

	const engine = triggerConditions.contextualEngine;
	return Boolean(engine && typeof engine === 'object');
}

/** Parcours publiés depuis le lab SDK (`/dashboard/sdk-tests/*` + moteur contextuel). */
export function isSdkLabPublishedTour(tour: TourLabEligibility): boolean {
	const targetUrl = normalizeTourPath(tour.targetUrl);
	if (!targetUrl.includes(SDK_LAB_TARGET_PATH_SEGMENT)) {
		return false;
	}

	return isContextualAutogeneratedTour(tour);
}

export function getContextualPublishedByRole(tour: TourLabEligibility): string | undefined {
	const engine = tour.triggerConditions?.contextualEngine;
	if (!engine || typeof engine !== 'object') {
		return undefined;
	}
	const role = (engine as { publishedByRole?: unknown }).publishedByRole;
	return typeof role === 'string' ? role : undefined;
}

/** Parcours autogénérés visibles uniquement en mode test développeur (legacy production). */
export function isDeveloperOnlyAutogenTour(
	tour: TourLabEligibility & Pick<GuidedTour, 'environment' | 'sandboxStatus'>,
): boolean {
	if (!isContextualAutogeneratedTour(tour)) {
		return false;
	}
	if (tour.environment === 'sandbox') {
		return false;
	}
	if (tour.sandboxStatus === 'approved') {
		return false;
	}
	if (getContextualPublishedByRole(tour) === 'ADMIN') {
		return false;
	}
	return true;
}

export function isDeveloperOwnedTestTour(
	tour: Pick<GuidedTour, 'createdBy' | 'environment' | 'sandboxStatus' | 'targetUrl' | 'triggerConditions'>,
	userId?: string,
): boolean {
	if (!userId || tour.createdBy !== userId) {
		return false;
	}
	return tour.environment === 'sandbox' || isDeveloperOnlyAutogenTour(tour);
}

export function normalizeTourPath(url?: string): string {
	return (url ?? '').toLowerCase().split('?')[0];
}

export function isSdkLabTargetPath(url?: string): boolean {
	return normalizeTourPath(url).includes(SDK_LAB_TARGET_PATH_SEGMENT);
}

/** Templates lab SDK : pas d’édition via l’éditeur parcours (test SDK uniquement). */
export function canManageLabPublishedTour(
	_tour: TourLabEligibility & Pick<GuidedTour, 'createdBy'>,
	_role: DashboardRole | null,
	_userId?: string,
): boolean {
	return false;
}

export function isSdkLabTemplateTour(tour: TourLabEligibility): boolean {
	return isSdkLabPublishedTour(tour);
}

export function canManageTour(
	tour: TourLabEligibility & TourSandboxFields,
	role: DashboardRole | null,
	userId?: string,
): boolean {
	if (isSdkLabTemplateTour(tour)) {
		return false;
	}
	return (
		canManageTours(role) ||
		canManageLabPublishedTour(tour, role, userId) ||
		canManageSandboxTour(tour, role, userId) ||
		hasTourAccessGrant(tour, userId, 'collaborate')
	);
}

export function canDeleteTour(
	tour: TourLabEligibility &
		TourSandboxFields &
		Pick<
			GuidedTour,
			| 'assignedAdminIds'
			| 'assignedToAdminsAt'
			| 'sandboxRejectedBy'
			| 'accessGrants'
			| 'createdBy'
			| 'inCollaboration'
		>,
	role: DashboardRole | null,
	userId?: string,
): boolean {
	if (isTourProductionDeployment(tour)) {
		return false;
	}
	if (isTourCardViewOnly(tour, role, userId) || isTourCollaborationPeerCard(tour, role, userId)) {
		return false;
	}
	if (isSdkLabTemplateTour(tour)) {
		return Boolean(userId) && tour.createdBy === userId;
	}
	if (canManageTours(role)) {
		return true;
	}
	return canDeveloperDeleteOwnedSandboxTour(tour, userId);
}

export function canOpenTourEditor(
	tour: TourLabEligibility & TourSandboxFields,
	role: DashboardRole | null,
	userId?: string,
	accessParam?: string | null,
): boolean {
	if (isTourProductionDeployment(tour)) {
		return false;
	}
	if (canAccessTourEditor(tour, role, userId, accessParam)) {
		return true;
	}
	if (!accessParam && canManageLabPublishedTour(tour, role, userId)) {
		return true;
	}
	return false;
}

/** Édition développeur d'un parcours publié depuis le lab (champs restreints). */
export function isDeveloperLabEditMode(
	tour: TourLabEligibility & Pick<GuidedTour, 'createdBy'>,
	role: DashboardRole | null,
	userId?: string,
): boolean {
	if (!canManageLabPublishedTour(tour, role, userId)) {
		return false;
	}
	return !isDeveloperOwnedSandboxTour(tour, userId);
}

/** Champs modifiables par un développeur sur un parcours lab (miroir backend). */
export const DEVELOPER_LAB_ALLOWED_UPDATE_FIELDS = ['name', 'description', 'steps'] as const;

/** Payload API strict pour sauvegarde développeur / parcours lab. */
export function pickDeveloperLabTourSavePayload(tour: GuidedTour): GuidedTourSavePayload {
	return {
		name: tour.name,
		description: tour.description,
		steps: (tour.steps || []).map((step) => {
			const {
				id: _id,
				orderIndex: _orderIndex,
				tourId: _tourId,
				createdAt: _createdAt,
				updatedAt: _updatedAt,
				concatSourceMeta: _concatSourceMeta,
				...safeStep
			} = step as GuidedTour['steps'][number] & { concatSourceMeta?: unknown };

			const stepTargetUrl = safeStep.stepTargetUrl?.trim();
			if (stepTargetUrl && !isSdkLabTargetPath(stepTargetUrl)) {
				const { stepTargetUrl: _removed, ...withoutUrl } = safeStep;
				return withoutUrl;
			}

			return safeStep;
		}),
	};
}
