import type { GuidedTour } from '@/lib/types';
import type { DashboardRole } from '@/lib/dashboard-roles';
import { canManageTours } from '@/lib/dashboard-roles';
import {
	canDeleteTour,
	isContextualAutogeneratedTour,
	isDeveloperOnlyAutogenTour,
	isSdkLabPublishedTour,
	isSdkLabTemplateTour,
} from '@/lib/tour-lab';
import {
	canAdminTransferProductionToSandbox,
	canAdminTransferSandboxToProduction,
	canAdminTransferTourEnvironment,
	canDelegateProductionManagement,
	isAdminOriginatedProductionTour,
	isProductionManagerAdmin,
	resolveProductionManagerAdminId,
	canApproveSandboxTour,
	canEditTourWithGrants,
	canReassignApprovedTourAdmins,
	canReopenApprovedDeveloperTour,
	canTransferApprovedDeveloperTour,
	canRejectSandboxTour,
	canToggleAdminProduction,
	canToggleAdminSandboxTest,
	hasTourAccessGrant,
	isTourCardViewOnly,
	isTourCollaborationPeerCard,
	isDeveloperModerationRejectedTour,
	isDeveloperModerationReturnedTour,
	isNewOwnerOfTransferredTour,
	isPreviousOwnerOfTransferredTour,
	isDeveloperPrivateUnassigned,
	isTourOwnerPrivateUnshared,
	isTourSharedWithMembers,
	isDeveloperOwnedAwaitingAdminDecision,
	isDeveloperSubmittedPendingSandbox,
	isDeveloperModerationApprovedSandbox,
	isDeveloperOriginatedTour,
	isTourProductionActive,
	isTourSandboxTestActive,
	type TourCreatorRoleLookup,
	type TourListEnvironmentFilter,
} from '@/lib/tour-sandbox';

export function resolveTourCardDisplayName(
	tour: Pick<GuidedTour, 'name' | 'targetUrl'>,
	isAutogen: boolean,
): string {
	const trimmed = tour.name?.trim();
	if (trimmed) {
		return trimmed;
	}
	if (isAutogen) {
		const path = tour.targetUrl?.trim();
		return path ? `Parcours autogénéré — ${path}` : 'Parcours autogénéré';
	}
	return 'Sans nom';
}

export type TourListEntryMeta = {
	searchHay: string;
	isSandbox: boolean;
	isAutogen: boolean;
	isLab: boolean;
	/** Template lab SDK : hors workflow parcours réel. */
	isLabTemplate: boolean;
	canLabTemplateDelete: boolean;
	canLabTemplateExport: boolean;
	isDevOnlyAutogen: boolean;
	/** Sandbox + `pending` + auteur développeur — file modération. */
	isDeveloperModerationPending: boolean;
	/** Propriétaire développeur : parcours assigné, en attente décision admin. */
	isDeveloperAwaitingAdminDecision: boolean;
	isDeveloperModerationRejected: boolean;
	isDeveloperModerationReturned: boolean;
	/** Ancien propriétaire après transfert — badge Transféré distinct. */
	showTransferredBadgePreviousOwner: boolean;
	/** Nouveau propriétaire — phase transférée (badge Transféré, sans Owner/Lecture/Retour). */
	showTransferredBadgeNewOwner: boolean;
	isDeveloperPrivateUnassigned: boolean;
	isInCollaboration: boolean;
	/** Propriétaire : parcours non partagé (badge Privé). */
	showPrivateOwnerBadge: boolean;
	/** Propriétaire : parcours partagé lecture/collab (badge Owner). */
	showOwnerRoleBadge: boolean;
	/** Tous les participants : partage lecture seule actif sur le parcours. */
	showSharingLectureBadge: boolean;
	/** Tous les participants : collaboration sandbox partagée. */
	showSharingCollabBadge: boolean;
	isApprovedSandbox: boolean;
	canManage: boolean;
	canDelete: boolean;
	/** Utilisateur courant = auteur du parcours (`createdBy`). */
	isOwner: boolean;
	/** Accès lecture seule (grant) : carte limitée export + test. */
	isViewOnlyCard: boolean;
	/** Pair collaboration sandbox (dev ou admin invité) : éditer + export + test. */
	isCollaborationPeerCard: boolean;
	canCollaborationPeerEdit: boolean;
	showApprove: boolean;
	showReject: boolean;
	showReopenToDeveloper: boolean;
	showReassignAdmins: boolean;
	showTransferDeveloper: boolean;
	showSandboxTestToggle: boolean;
	showProductionToggle: boolean;
	/** Réactivation audience (prod) — masquée tant que le parcours n’est pas en production. */
	showAudienceReset: boolean;
	/** Admin : bascule sandbox ↔ production sur la carte (hors éditeur). */
	showEnvironmentSwitcher: boolean;
	/** Admin : bouton Prod du switcher (false si rejeté / en attente modération développeur). */
	canTransferToProduction: boolean;
	/** Admin : bouton Sandbox du switcher (false si non propriétaire sur parcours admin en prod). */
	canTransferToSandbox: boolean;
	/** Admin : gestionnaire prod effectif (activation, export, délégation). */
	canManageProductionDeployment: boolean;
	/** Propriétaire créateur : déléguer / reprendre la gestion prod. */
	showDelegateProductionManagement: boolean;
	/** Gestion prod déléguée à un autre admin que le créateur. */
	showProductionDelegatedBadge: boolean;
	productionManagerUserId: string | null;
	/** Parcours développeur approuvé puis promu en prod — reste visible dans le filtre sandbox développeur. */
	isDeveloperOwnedApprovedProduction: boolean;
	sandboxTestActive: boolean;
	productionActive: boolean;
	isActiveTestLabel: boolean;
};

export type TourListEntry = {
	tour: GuidedTour;
	meta: TourListEntryMeta;
};

export type TourListStats = {
	total: number;
	active: number;
	sandbox: number;
	autogen: number;
	pendingSandbox: number;
};

export type TourListIndex = {
	entries: TourListEntry[];
	stats: TourListStats;
};

function buildSearchHay(tour: GuidedTour): string {
	return [
		tour.targetUrl,
		tour.name,
		tour.description,
		typeof tour.id === 'string' ? tour.id : '',
	]
		.filter(Boolean)
		.join(' ')
		.toLowerCase();
}

export function buildTourListIndex(
	tours: GuidedTour[],
	role: DashboardRole | null,
	userId: string | undefined,
	isAdmin: boolean,
	creatorRoleByUserId?: TourCreatorRoleLookup,
): TourListIndex {
	const canManageAll = canManageTours(role);
	const isDeveloper = role === 'DEVELOPER';

	const stats: TourListStats = {
		total: 0,
		active: 0,
		sandbox: 0,
		autogen: 0,
		pendingSandbox: 0,
	};

	const entries: TourListEntry[] = [];

	for (const tour of tours) {
		stats.total += 1;
		if (tour.isActive) {
			stats.active += 1;
		}

		const isSandbox = tour.environment === 'sandbox';
		const isAutogen = isContextualAutogeneratedTour(tour);
		const isDevOnlyAutogen = isDeveloperOnlyAutogenTour(tour);
		const isLab = isSdkLabPublishedTour(tour);
		const isLabTemplate = isSdkLabTemplateTour(tour);
		const viewer = { role, userId };
		const isDeveloperModerationPending = isDeveloperSubmittedPendingSandbox(
			tour,
			creatorRoleByUserId,
			viewer,
		);
		const isOwner = Boolean(userId) && tour.createdBy === userId;
		const isDeveloperAwaitingAdminDecision =
			isDeveloper && isOwner && isDeveloperOwnedAwaitingAdminDecision(tour, userId);
		const isDeveloperModerationRejected = isDeveloperModerationRejectedTour(tour, creatorRoleByUserId);
		const showTransferredBadgePreviousOwner = isPreviousOwnerOfTransferredTour(tour, userId);
		const showTransferredBadgeNewOwner = isNewOwnerOfTransferredTour(tour, userId);
		const isDeveloperModerationReturned =
			isDeveloperModerationReturnedTour(tour, userId) &&
			!showTransferredBadgeNewOwner &&
			!showTransferredBadgePreviousOwner;
		const isDevPrivateUnassigned = isDeveloperPrivateUnassigned(tour);
		const isApprovedSandbox = isDeveloperModerationApprovedSandbox(
			tour,
			creatorRoleByUserId,
		);
		const isSharedWithMembers = isTourSharedWithMembers(tour);
		const actorHasViewGrant = hasTourAccessGrant(tour, userId, 'view');
		const actorHasCollabGrant = hasTourAccessGrant(tour, userId, 'collaborate');
		const showPrivateOwnerBadge =
			isTourOwnerPrivateUnshared(tour, userId, creatorRoleByUserId) &&
			!showTransferredBadgeNewOwner;
		const showOwnerRoleBadge = isOwner && isSharedWithMembers && !showTransferredBadgeNewOwner;
		const showSharingLectureBadge =
			(actorHasViewGrant || (isOwner && Boolean(tour.sharingHasView))) &&
			!showTransferredBadgeNewOwner;
		const showSharingCollabBadge =
			actorHasCollabGrant || (isOwner && Boolean(tour.sharingHasCollaborate));

		if (isSandbox) {
			stats.sandbox += 1;
		}
		if (isAutogen) {
			stats.autogen += 1;
		}
		if (isDeveloperModerationPending) {
			stats.pendingSandbox += 1;
		}

		const canManageSandbox =
			isDeveloper &&
			isSandbox &&
			isOwner &&
			tour.sandboxStatus !== 'approved' &&
			!isDeveloperAwaitingAdminDecision;
		const canManageLabTour = false;
		const canManageDevTest =
			isDeveloper &&
			isOwner &&
			(isSandbox || isDevOnlyAutogen) &&
			!isDeveloperAwaitingAdminDecision;
		const canAdminEnvTransfer = canAdminTransferTourEnvironment(
			tour,
			role,
			userId,
			creatorRoleByUserId,
		);
		const showEnvironmentSwitcher =
			!isLabTemplate && canAdminEnvTransfer && !isDeveloperModerationPending;
		const canTransferToProduction = canAdminTransferSandboxToProduction(
			tour,
			creatorRoleByUserId,
		);
		const canTransferToSandbox = canAdminTransferProductionToSandbox(
			tour,
			role,
			userId,
			creatorRoleByUserId,
		);
		const isAdminProdTour = isAdminOriginatedProductionTour(tour, creatorRoleByUserId);
		const productionManagerUserId = isAdminProdTour
			? resolveProductionManagerAdminId(tour)
			: null;
		const canManageProductionDeployment =
			!isAdminProdTour || isProductionManagerAdmin(tour, userId, creatorRoleByUserId);
		const showDelegateProductionManagement = canDelegateProductionManagement(
			tour,
			role,
			userId,
			creatorRoleByUserId,
		);
		const showProductionDelegatedBadge =
			isAdminProdTour &&
			Boolean(productionManagerUserId) &&
			productionManagerUserId !== tour.createdBy;
		const isDeveloperOwnedApprovedProduction =
			isDeveloper &&
			isOwner &&
			tour.environment === 'production' &&
			tour.sandboxStatus === 'approved' &&
			isDeveloperOriginatedTour(tour, creatorRoleByUserId);
		const isViewOnlyCard = isTourCardViewOnly(tour, role, userId);
		const isCollaborationPeerCard = isTourCollaborationPeerCard(tour, role, userId);
		const canCollaborationPeerEdit = isCollaborationPeerCard && canEditTourWithGrants(tour, role, userId);
		const effectiveEnvSwitcher =
			!isLabTemplate && showEnvironmentSwitcher && !isViewOnlyCard && !isCollaborationPeerCard;
		entries.push({
			tour,
			meta: {
				searchHay: buildSearchHay(tour),
				isSandbox,
				isAutogen,
				isLab,
				isLabTemplate,
				canLabTemplateDelete: isLabTemplate && isOwner,
				canLabTemplateExport: isLabTemplate && isOwner,
				isDevOnlyAutogen,
				isDeveloperModerationPending,
				isDeveloperAwaitingAdminDecision,
				isDeveloperModerationRejected,
				isDeveloperModerationReturned,
				showTransferredBadgePreviousOwner,
				showTransferredBadgeNewOwner,
				isDeveloperPrivateUnassigned: isDevPrivateUnassigned,
				isInCollaboration: Boolean(tour.inCollaboration),
				showPrivateOwnerBadge,
				showOwnerRoleBadge,
				showSharingLectureBadge: !isLabTemplate && showSharingLectureBadge,
				showSharingCollabBadge: !isLabTemplate && showSharingCollabBadge,
				isApprovedSandbox,
				canManage: !isLabTemplate && (canManageAll || canManageSandbox),
				canDelete: isLabTemplate ? isOwner : canDeleteTour(tour, role, userId),
				isOwner,
				isViewOnlyCard,
				isCollaborationPeerCard,
				canCollaborationPeerEdit,
				showApprove:
					!isLabTemplate && canApproveSandboxTour(tour, role, creatorRoleByUserId, userId),
				showReject:
					!isLabTemplate && canRejectSandboxTour(tour, role, creatorRoleByUserId, userId),
				showReopenToDeveloper: canReopenApprovedDeveloperTour(
					tour,
					role,
					creatorRoleByUserId,
					userId,
				),
				showReassignAdmins: canReassignApprovedTourAdmins(
					tour,
					role,
					creatorRoleByUserId,
					userId,
				),
				showTransferDeveloper: canTransferApprovedDeveloperTour(
					tour,
					role,
					creatorRoleByUserId,
					userId,
				),
				showEnvironmentSwitcher: effectiveEnvSwitcher,
				canTransferToProduction,
				canTransferToSandbox,
				canManageProductionDeployment,
				showDelegateProductionManagement: !isLabTemplate && showDelegateProductionManagement,
				showProductionDelegatedBadge,
				productionManagerUserId,
				showSandboxTestToggle:
					!isLabTemplate &&
					!effectiveEnvSwitcher &&
					(isViewOnlyCard ||
						isCollaborationPeerCard ||
						canManageDevTest ||
						(isAdmin && canToggleAdminSandboxTest(tour, role))),
				showProductionToggle:
					!isLabTemplate &&
					!effectiveEnvSwitcher &&
					!isViewOnlyCard &&
					!isCollaborationPeerCard &&
					isAdmin &&
					canToggleAdminProduction(tour, role) &&
					!isDevOnlyAutogen,
				showAudienceReset:
					!isLabTemplate &&
					isAdmin &&
					!isViewOnlyCard &&
					!isCollaborationPeerCard &&
					tour.environment === 'production' &&
					canManageProductionDeployment,
				isDeveloperOwnedApprovedProduction,
				sandboxTestActive: isTourSandboxTestActive(tour),
				productionActive: isTourProductionActive(tour),
				isActiveTestLabel:
					isTourSandboxTestActive(tour) && (isSandbox || isDevOnlyAutogen),
			},
		});
	}

	return { entries, stats };
}

export function filterTourListEntries(
	entries: TourListEntry[],
	filterQuery: string,
	environmentFilter: TourListEnvironmentFilter,
): TourListEntry[] {
	const query = filterQuery.trim().toLowerCase();
	if (!query && environmentFilter === 'all') {
		return entries;
	}

	return entries.filter(({ tour, meta }) => {
		if (!matchesTourMetaEnvironmentFilter(meta, environmentFilter)) {
			return false;
		}
		if (!query) {
			return true;
		}
		return meta.searchHay.includes(query);
	});
}

export function matchesTourMetaEnvironmentFilter(
	meta: Pick<
		TourListEntryMeta,
		| 'isSandbox'
		| 'isDevOnlyAutogen'
		| 'isDeveloperModerationPending'
		| 'showSharingLectureBadge'
		| 'showSharingCollabBadge'
		| 'isDeveloperOwnedApprovedProduction'
	>,
	filter: TourListEnvironmentFilter,
): boolean {
	switch (filter) {
		case 'production':
			return !meta.isSandbox;
		case 'sandbox':
			return meta.isSandbox || meta.isDevOnlyAutogen || meta.isDeveloperOwnedApprovedProduction;
		case 'pending':
			return meta.isDeveloperModerationPending;
		case 'lecture':
			return meta.showSharingLectureBadge;
		case 'collab':
			return meta.showSharingCollabBadge;
		default:
			return true;
	}
}
